### ISSUE TITLE
Fences/Walls Don't Connect

### ISSUE THREAD

**Issue by WenXin20** [LordGrimmauld/windowlogging#2]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Windowlogging v0.0.1`

Fences and walls don't connect to each other or other blocks once they are windowlogged.

Edit: Another minor one is that the Turf slabs from Quark loses it's tint, and slabs that emit light won't once windowlogged.

**Comment by LordGrimmauld** [comment]
i am not sure i can do tint, i can try though. The light emission is easy, i will definitely add that soon.
I am not yet sure whether i actually like fences and walls not connecting, as it makes for a few interesting build options:
![unknown](https://user-images.githubusercontent.com/49513131/93689868-fba21100-fad2-11ea-826c-8a969a03172c.png)
I might consider adding a config for this, or add a tool that can togge this behaviour. I will definitely keep walls and fences in the back of my mind, though it is not the highest priority right now.

**Comment by WenXin20** [comment]
Ok, that's a good point, and a tool is a good idea. Though another thing to note is that I was able to jump over the fence after windowlogging, maybe it's not taking the collision height into account?

**Comment by WenXin20** [comment]
Does this help for tint? Double Slabs has a similar issue and was fixed. CJMinecraft01/DoubleSlabs#129

**Comment by LordGrimmauld** [comment]
i decided there is not much i can do against the fences not connecting, but i did manage to finally fix the tinting. In the future, please report different issues in seperate issue tickets, then its easier to keep track of what is actually a problem still, ty
